### ISSUE TITLE
Add Stronger Threshold Support

### ISSUE THREAD

**Issue by harningt** [Vonage/Grafana_Status_panel#14]
The current threshold system assumes that larger values are a problem.

In a current use-case I have, larger values are a good thing (indicating number of operational systems).

**Comment by TomerAmirV** [comment]
Hello @harningt ,
This feature is in the current version of the plugin, although it needs to be documented since you are not the first one to ask.

When you set a critical threshold lower than the warning threshold, it is detected and treats higher values as "good", and lower values as "bad".

Please check that is works for you, and feel free to reopen this issue if you still have any problems.
