### ISSUE TITLE
Vrong value

### ISSUE THREAD

**Issue by digi-tecnodata** [Vonage/Grafana_Status_panel#30]
On grafana 4.1.2 I installed the latest status panel version (1.0.1).
For testing I added one status panel and one singlestat panel with the same query on the metric tab to see the differences between them but I noticed the values displayed were different.
I installed the panel through grafana-cli command.
What can I do to solve the problem?

Thanks
![statuspanel](https://cloud.githubusercontent.com/assets/25297988/23563515/466a473c-0047-11e7-9d56-84740e9691d0.jpg)

**Comment by TomerAmirV** [comment]
Hello @digi-tecnodata 
It seems to me like this is an aggregation issue, or a unit selection issue. It's hard for me to guess without seeing the query and the results, but I would play with the aggregation field and see if anything changes.

Please update us if this solves your issue or not.

**Comment by digi-tecnodata** [comment]
Thanks for you reply.
I configured the aggregation field to none to view the current value and where I can modify the unit? I can't view the unit field in status panel options.
The query is: alias(collectd.myserver.GenericJMX-java_memory.memory-heap-used, 'heap_used') using graphite data source.
On singlestat panel I used the same query and on the unit field I select none.
I attach the screenshot of metrics and options tab on the status panel.

Tahnks
![statuspanel](https://cloud.githubusercontent.com/assets/25297988/23602784/68b0e7c6-0252-11e7-8b67-f2b832b147fb.jpg)

**Comment by TomerAmirV** [comment]
Hi,

what I meant was that if you get back more than one result from the query, by selecting `None` in the status panel you get a different result from the one selected in the single stat panel.

I did just approve a pull request which changes the name of the `None` field to `Last`, and also added a new option `First`, but I still haven released the new version using Grafanas repo. You could clone the plugin directly from this repo and try. There are instructions on how to do it in the README file under the installation instructions for debugging.

You could also wait for the next version, but that might take a few more days since I am waiting for some other development to be released first.

**Comment by digi-tecnodata** [comment]
Thanks for your reply, I removed the plugin and I installed it from github and now all work fine.
